---
title: "Day 2 Assignments"
author: "Paloma Cartwright"
date: "03/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
```

### First Order Univariate Derivates 

Find the derivative expression and slope at the indicated value for each of the following 

Question A 

$f(x) = x^2$ at $x = 3$

```{r}

fx <- expression(x^2)

df_dx <- D(expr = fx, name = "x")

df_dx

x <- 3 

eval(expr = df_dx)

```


Question B 

$P(a) = 2(3a+2)^4 - 5$ at $a = 1.2$

```{r}

Pa <- expression(2 * (3 * a + 2) ^ 4 - 5)

dP_da <- D(expr = Pa, name = "a")

dP_da

a <- 1.2 

eval(expr = dP_da)

```

Question C 

$g(t) = (-4t)/(t^2+1)^3)$ at $t = 0$

```{r}
gt <- expression((-4 * t)*((t^2 + 1)^-3))

dg_dt <- D(expr = gt, name = "t")
dg_dt

t <- 0

eval(expr = dg_dt)


```

### Higher Order Univariate Derivatives

Find the second derivative with respect to z for $G(z) = 4.6 - 1.9z^3$.

```{r}

Gz <- expression(4.6 - 1.9 * z ^ 3)
#First derivative
dG_dz <- D(expr = Gz, name = "z")
dG_dz
#Second derivative
d2G_dz2 <- D(expr = dG_dz, name = "z")
d2G_dz2

```

